name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Update version in __init__.py
        id: update_version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          sed -i 's/__version__ = .*/__version__ = '\''$VERSION'\''/' actions/__init__.py

          if git diff --quiet actions/__init__.py; then
            echo "version_updated=false" >> $GITHUB_OUTPUT
          else
            echo "version_updated=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.update_version.outputs.version_updated == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add actions/__init__.py
          git commit -m "[CI] - Update version to ${{ steps.get_version.outputs.VERSION }}"
          git push

      - name: Create new tag
        if: steps.update_version.outputs.version_updated == 'true'
        run: |
          git tag -f ${GITHUB_REF#refs/tags/}
          git push -f origin ${GITHUB_REF#refs/tags/}
